name: Build README

on:
  workflow_dispatch:
  schedule:
    - cron: "5 0 * * *"

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'  # 启用 Python 依赖缓存

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run Python script
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: python build_readme.py README.md

      - name: Commit and push if changed
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "ci: update README [skip ci]" && git push)